name: ci

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          server-id: sonatype.snapshots
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          distribution: 'temurin'
          java-version: 17
          cache: maven
      - name: Build & Test & Deploy
        run: ./mvnw -B deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}